### ISSUE TITLE
Automatic releasing to pypy

### ISSUE THREAD

**Issue by kralka** [google/sedpack#51]
Do a workflow for releasing a pip package

https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

Might need patchelf https://www.maturin.rs/installation.html

**Comment by wsxrdv** [comment]
https://github.com/google/sedpack/pull/58 had a workaround in .github/actions/maturin to install xxhash, remove this

**Comment by kralka** [comment]
Fixed by https://github.com/google/sedpack/pull/74
